# DSC 495: Final Project Data Cleaning

In [15]:
import pandas as pd
import os

## Reading in Data

In [16]:
directory = './data/raw_data/'
files = os.listdir(directory)
datasets = []

for file in files: 
    datasets.append(pd.read_csv(directory + file))

## Data Cleaning

In [17]:
#combine datasets
flight_delays = pd.concat(datasets)
flight_delays.head()

,YEAR,MONTH,ORIGIN,ORIGIN_STATE_NM,DEST,DEST_STATE_NM,DEP_DELAY,DEP_DELAY_NEW,ARR_DELAY,ARR_DELAY_NEW,CANCELLED,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2020,9,SEA,Washington,DEN,Colorado,-12.0,0.0,-6.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
1,2020,9,SEA,Washington,ATL,Georgia,-2.0,0.0,-11.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2,2020,9,ANC,Alaska,SEA,Washington,-9.0,0.0,-10.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
3,2020,9,CDB,Alaska,ADK,Alaska,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN
4,2020,9,SEA,Washington,JNU,Alaska,-6.0,0.0,-1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN

In [18]:
#create variable for total delay in minutes and name of month
month_dictionary = {1: 'January', 
                    2: 'February', 
                    3: 'March', 
                    4: 'April',
                    5: 'May', 
                    6: 'June', 
                    7: 'July', 
                    8: 'August', 
                    9: 'September', 
                    10: 'October', 
                    11: 'November', 
                    12: 'December'}
        
flight_delays['MONTH_NAME'] = flight_delays['MONTH'].apply(lambda x: month_dictionary[x])   
flight_delays['TOT_DELAY'] = flight_delays['CARRIER_DELAY'] + flight_delays['WEATHER_DELAY'] + flight_delays['NAS_DELAY'] + flight_delays['SECURITY_DELAY'] + flight_delays['LATE_AIRCRAFT_DELAY']

flight_delays

,YEAR,MONTH,ORIGIN,ORIGIN_STATE_NM,DEST,DEST_STATE_NM,DEP_DELAY,DEP_DELAY_NEW,ARR_DELAY,ARR_DELAY_NEW,CANCELLED,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,MONTH_NAME,TOT_DELAY
0,2020,9,SEA,Washington,DEN,Colorado,-12.0,0.0,-6.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,September,NaN
1,2020,9,SEA,Washington,ATL,Georgia,-2.0,0.0,-11.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,September,NaN
2,2020,9,ANC,Alaska,SEA,Washington,-9.0,0.0,-10.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,September,NaN
3,2020,9,CDB,Alaska,ADK,Alaska,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,September,NaN
4,2020,9,SEA,Washington,JNU,Alaska,-6.0,0.0,-1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,September,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223727,2020,6,CLL,Texas,DFW,Texas,-7.0,0.0,2.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,June,NaN
223728,2020,6,CLL,Texas,DFW,Texas,-5.0,0.0,9.0,9.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,June,NaN
223729,2020,6,CLL,Texas,DFW,Texas,-8.0,0.0,2.0,2.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,June,NaN
223730,2020,6,CLL,Texas,DFW,Texas,-4.0,0.0,15.0,15.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,June,15.0
223731,2020,6,CLL,Texas,DFW,Texas,-14.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,June,NaN

In [19]:
flight_delays.to_csv('./data/processed_data/flight_delays.csv')